sudo: false
language: php
php:
  - "5.5"
  - "5.6"
  - "nightly"
  - "hhvm"

before_script:
  - composer install

script: 
  - bin/phpunit --coverage-text

matrix:
     allow_failures:
         - php: "hhvm"
